# Dependencies
# markdown:         redcarpet
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

safe:             true
lsi:              false
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Антон Ларкин'
tagline:          'Блог о интересах'
description:      'Фантастический блог фантастичен!'
url:              http://toxicwar.github.io/

author:
  name:           'Антон Ларкин'
  github:         https://github.com/ToxicWar
  twitter:        https://twitter.com/toxic_war

paginate:         5

# Custom vars
